In [29]:
import pandas as pd

In [30]:
df = pd.read_excel('data/raw/raw_data.xlsx')

In [31]:
nuevas_columnas = ['actividad','Ventas','ventas_post','personas','personas_post','locales','residenciales','tiempo','tiempo_post'] 
for i in range(9):
    df = df.rename(columns={
        df.columns[i+1]:nuevas_columnas[i] 
    })
df.sort_values(by='actividad', ascending=False)

,Marca temporal,actividad,Ventas,ventas_post,personas,personas_post,locales,residenciales,tiempo,tiempo_post
12,2025-05-13 10:49:20,independiente,0,0,0,0,10,25,10,-10
19,2025-05-13 11:39:26,independiente,-35,45,-20,30,25,30,15,-20
3,2025-05-13 09:48:11,independiente,-25,35,-10,25,10,20,10,-15
18,2025-05-13 11:29:22,independiente,-30,40,-10,20,10,20,15,-20
14,2025-05-13 10:57:54,independiente,-20,30,-15,15,10,15,20,-25
1,2025-05-13 09:35:43,independiente,-45,40,-5,10,25,25,20,-25
0,2025-05-13 09:35:08,empleado,-30,30,-30,50,40,55,10,-35
17,2025-05-13 11:23:09,empleado,-20,25,-50,45,10,40,20,-20
16,2025-05-13 11:17:55,empleado,-30,30,-30,50,40,55,15,-35
15,2025-05-13 11:08:30,empleado,-20,20,-45,45,10,40,20,-20
13,2025-05-13 10:50:58,empleado,-30,30,-25,55,40,55,10,-35
10,2025-05-13 10:25:13,empleado,-35,35,-25,60,40,60,5,-30
11,2025-05-13 10:34:12,empleado,-25,25,-35,40,10,50,15,-25
9,2025-05-13 10:20:21,empleado,-20,20,-40,45,10,40,20,-20
8,2025-05-13 10:17:39,empleado,-25,30,-40,40,10,50,10,-25
7,2025-05-13 10:04:36,empleado,-25,25,-40,40,10,50,15,-25
6,2025-05-13 10:02:40,empleado,-30,120,-35,100,40,55,10,-35
5,2025-05-13 09:56:25,empleado,-35,35,-30,60,40,60,5,-30
4,2025-05-13 09:53:11,empleado,-35,30,-45,55,40,60,5,-30
2,2025-05-13 09:46:53,empleado,-25,120,-50,40,10,50,15,-25
20,2025-05-13 11:44:03,empleado,-20,20,-50,45,10,40,20,-35

In [32]:
for c in df.columns[2:]:
    for v in df[c]:
        if v < 0:
            df[c] = df[c]*-1
            break

In [33]:
df['diff_tiempo'] = df['tiempo'] - df['tiempo_post']

In [34]:
df

,Marca temporal,actividad,Ventas,ventas_post,personas,personas_post,locales,residenciales,tiempo,tiempo_post,diff_tiempo
0,2025-05-13 09:35:08,empleado,30,30,30,50,40,55,10,35,-25
1,2025-05-13 09:35:43,independiente,45,40,5,10,25,25,20,25,-5
2,2025-05-13 09:46:53,empleado,25,120,50,40,10,50,15,25,-10
3,2025-05-13 09:48:11,independiente,25,35,10,25,10,20,10,15,-5
4,2025-05-13 09:53:11,empleado,35,30,45,55,40,60,5,30,-25
5,2025-05-13 09:56:25,empleado,35,35,30,60,40,60,5,30,-25
6,2025-05-13 10:02:40,empleado,30,120,35,100,40,55,10,35,-25
7,2025-05-13 10:04:36,empleado,25,25,40,40,10,50,15,25,-10
8,2025-05-13 10:17:39,empleado,25,30,40,40,10,50,10,25,-15
9,2025-05-13 10:20:21,empleado,20,20,40,45,10,40,20,20,0
10,2025-05-13 10:25:13,empleado,35,35,25,60,40,60,5,30,-25
11,2025-05-13 10:34:12,empleado,25,25,35,40,10,50,15,25,-10
12,2025-05-13 10:49:20,independiente,0,0,0,0,10,25,10,10,0
13,2025-05-13 10:50:58,empleado,30,30,25,55,40,55,10,35,-25
14,2025-05-13 10:57:54,independiente,20,30,15,15,10,15,20,25,-5
15,2025-05-13 11:08:30,empleado,20,20,45,45,10,40,20,20,0
16,2025-05-13 11:17:55,empleado,30,30,30,50,40,55,15,35,-20
17,2025-05-13 11:23:09,empleado,20,25,50,45,10,40,20,20,0
18,2025-05-13 11:29:22,independiente,30,40,10,20,10,20,15,20,-5
19,2025-05-13 11:39:26,independiente,35,45,20,30,25,30,15,20,-5
20,2025-05-13 11:44:03,empleado,20,20,50,45,10,40,20,35,-15

In [35]:
df.to_excel('data/cleaned/data.xlsx', index=False)